<?php

namespace ACL\ACLBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRolesRepository extends EntityRepository
{
}
