admin_quiz_preguntas:
    path:     /
    defaults: { _controller: "QuizBundle:Preguntas:index" }

admin_quiz_preguntas_show:
    path:     /{id}/show
    defaults: { _controller: "QuizBundle:Preguntas:show" }

admin_quiz_preguntas_new:
    path:     /new
    defaults: { _controller: "QuizBundle:Preguntas:new" }

admin_quiz_preguntas_create:
    path:     /create
    defaults: { _controller: "QuizBundle:Preguntas:create" }
    methods:  POST

admin_quiz_preguntas_edit:
    path:     /{id}/edit
    defaults: { _controller: "QuizBundle:Preguntas:edit" }

admin_quiz_preguntas_update:
    path:     /{id}/update
    defaults: { _controller: "QuizBundle:Preguntas:update" }
    methods:  [POST, PUT]

admin_quiz_preguntas_delete:
    path:     /{id}/delete
    defaults: { _controller: "QuizBundle:Preguntas:delete" }
    methods:  [POST, DELETE]

admin_quiz_respuestas_crear:
    path:     /respuesta-crear
    defaults: { _controller: "QuizBundle:Preguntas:crearRespuesta" }
    methods:  POST
