admin_quiz:
    path:     /
    defaults: { _controller: "QuizBundle:Quiz:index" }

admin_quiz_show:
    path:     /{id}/show
    defaults: { _controller: "QuizBundle:Quiz:show" }

admin_quiz_new:
    path:     /new
    defaults: { _controller: "QuizBundle:Quiz:new" }

admin_quiz_create:
    path:     /create
    defaults: { _controller: "QuizBundle:Quiz:create" }
    methods:  POST

admin_quiz_edit:
    path:     /{id}/edit
    defaults: { _controller: "QuizBundle:Quiz:edit" }

admin_quiz_update:
    path:     /{id}/update
    defaults: { _controller: "QuizBundle:Quiz:update" }
    methods:  [POST, PUT]

admin_quiz_delete:
    path:     /{id}/delete
    defaults: { _controller: "QuizBundle:Quiz:delete" }
    methods:  [POST, DELETE]
