<?php

namespace Quiz\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OpcionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcionesRepository extends EntityRepository
{
}
