<?php

namespace Quiz\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizOpcionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizOpcionesRepository extends EntityRepository
{
}
