front_home:
    path:     /
    defaults: { _controller: AppBundle:Front/Front:home }

front_curso:
    path:     /curso/{id}
    defaults: { _controller: AppBundle:Front/Curso:curso }

item_audio:
    path:     /curso/{curso}/{modulo}/{item}/audio
    defaults: { _controller: AppBundle:Front/ItemAudio:itemAudio, tipo:audio}
    requirements:
        tipo: audio

item_foro:
    path:     /curso/{curso}/{modulo}/{item}/foro
    defaults: { _controller: AppBundle:Front/ItemForo:itemForo, tipo:foro}
    requirements:
        tipo: foro

item_pdf:
    path:     /curso/{curso}/{modulo}/{item}/pdf
    defaults: { _controller: AppBundle:Front/ItemsFront:itemPDF, tipo:pdf}
    requirements:
        tipo: pdf

item_video:
    path:     /curso/{curso}/{modulo}/{item}/video
    defaults: { _controller: AppBundle:Front/ItemsFront:itemVideo, tipo:video}
    requirements:
        tipo: video

item_quiz:
    path:     /curso/{curso}/{modulo}/{item}/quiz
    defaults: { _controller: AppBundle:Front/ItemsFront:itemQuiz, tipo:quiz}
    requirements:
        tipo: quiz

item_audio_down:
    path:     /curso/{curso}/{modulo}/{item}/down
    defaults: { _controller: AppBundle:Front/ItemsFront:itemAudioDown, tipo:down}
    requirements:
        tipo: down

front_modulo:
    path:     /curso/{curso}/{modulo}/{item}/{pregunta}
    defaults: { _controller: AppBundle:Front/FrontModulo:modulo, pregunta:null }

front_perfil:
    path:     /perfil/
    defaults: { _controller: AppBundle:Front/Perfil:perfil }

perfil_tus_cursos:
    path:     /perfil/tus-cursos
    defaults: { _controller: AppBundle:Front/CursosUsuario:cursos }

front_msn:
    path:     /perfil/msn
    defaults: { _controller: AppBundle:Admin/MSN:msn}

front_soap:
    path:     /soap
    defaults: { _controller: AppBundle:Front/SoapServer:soapServer }

front_registro:
    path:     /soap/registro
    defaults: { _controller: AppBundle:Front/SoapCliente:soapCliente }
    requirements: { _method: post|get }

front_eliminar_mensaje:
    path:     /item/eliminar-mensaje/{curso}/{modulo}/{item}/{id}
    defaults: { _controller: AppBundle:Front/EliminarMensajeItem:eliminar }
