front_curso:
    path:     /curso/{id}
    defaults: { _controller: AppBundle:Front/Front:index }

front_modulo:
    path:     /curso/{curso}/{modulo}/{seccion}/{pregunta}
    defaults: { _controller: AppBundle:Front/Front:modulo, pregunta:null }

front_perfil:
    path:     /perfil/
    defaults: { _controller: AppBundle:Front/Perfil:perfil }

perfil_tus_cursos:
    path:     /perfil/tus-cursos
    defaults: { _controller: AppBundle:Front/CursosUsuario:cursos }

front_msn:
    path:     /perfil/msn
    defaults: { _controller: AppBundle:Admin/MSN:msn}
