front_home:
    path:     /
    defaults: { _controller: AppBundle:Front/Front:home }

front_curso:
    path:     /curso/{id}
    defaults: { _controller: AppBundle:Front/Curso:curso }

front_modulo:
    path:     /curso/{curso}/{modulo}/{item}/{pregunta}
    defaults: { _controller: AppBundle:Front/FrontModulo:modulo, pregunta:null }

front_perfil:
    path:     /perfil/
    defaults: { _controller: AppBundle:Front/Perfil:perfil }

perfil_tus_cursos:
    path:     /perfil/tus-cursos
    defaults: { _controller: AppBundle:Front/CursosUsuario:cursos }

front_msn:
    path:     /perfil/msn
    defaults: { _controller: AppBundle:Admin/MSN:msn}

front_soap:
    path:     /soap
    defaults: { _controller: AppBundle:Front/SoapServer:soapServer }

front_registro:
    path:     /soap/registro
    defaults: { _controller: AppBundle:Front/SoapCliente:soapCliente }
    requirements: { _method: post|get }
