login:
    pattern:   /login
    defaults:  { _controller: AppBundle:ACL/Login:login }

login_check:
    pattern:   /login_check

logout:
    path:   /logout

### Recuperar

acl_recuperar:
    path:     /recuperar
    defaults: { _controller: AppBundle:ACL/RecuperarCuenta:recuperar }

acl_recuperar_cuenta:
    path:     /recuperar/{codigo}
    defaults: { _controller: AppBundle:ACL/RecuperarCuenta:recuperarCuenta }
