login:
    pattern:   /login
    defaults:  { _controller: AppBundle:ACL/Login:login }

login_check:
    pattern:   /login_check

logout:
    path:   /logout

### Recuperar

acl_recuperar:
    path:     /recuperar
    defaults: { _controller: AppBundle:ACL/RecuperarCuenta:recuperar }

acl_recuperar_cuenta:
    path:     /cambiar-password/{codigo}
    defaults: { _controller: AppBundle:ACL/RecuperarCuenta:recuperarCuenta }

### Registro cuenta

acl_registro_cuenta:
    path:     /registro
    defaults: { _controller: AppBundle:ACL/RegistroCuenta:registro }


acl_activar_cuenta:
  path:     /activar-cuenta/{salt}
  defaults: { _controller: AppBundle:ACL/RegistroCuenta:activarCuenta }

acl_no_activo:
    path:     /no-activa
    defaults: { _controller: AppBundle:ACL/CuentaNoActiva:noActiva }

## Registro curso

acl_registro_curso:
    path:     /perfil/registro-curso/{id}/{sku}
    defaults: { _controller: AppBundle:ACL/RegistroCurso:registroCurso }


acl_cuenta_activada:
    path:     /registro/cuenta-activada
    defaults: { _controller: AppBundle:ACL/RegistroCuenta:cuentaActivada }
