usuarios:
    path:     /
    defaults: { _controller: "AppBundle:ACL/Usuarios:index" }

usuarios_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ACL/Usuarios:show" }

usuarios_new:
    path:     /new
    defaults: { _controller: "AppBundle:ACL/Usuarios:new" }

usuarios_create:
    path:     /create
    defaults: { _controller: "AppBundle:ACL/Usuarios:create" }
    methods:  POST

usuarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ACL/Usuarios:edit" }

usuarios_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:ACL/Usuarios:update" }
    methods:  [POST, PUT]

usuarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ACL/Usuarios:delete" }
    methods:  [POST, DELETE]
