<?php

namespace AppBundle\Entity\Admin;

use Doctrine\ORM\EntityRepository;

/**
 * ModuloSeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloSeccionesRepository extends EntityRepository
{
}
