<?php

namespace AppBundle\Entity\ACL;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository
{
    public function byUsernameOrEmail($username)
    {
        return $this->getEntityManager()
              ->createQuery(
                  'SELECT u FROM AppBundle:ACL\Usuarios u
                   WHERE u.username = :username
                   OR u.email = :email
                  '
              )
              ->setParameter('username', $username)
              ->setParameter('email', $username)
              ->getSingleResult();
    }
}
