admin_secciones:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Items:index" }

admin_secciones_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/Items:show" }

admin_secciones_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Items:new" }

admin_secciones_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/Items:create" }
    requirements: { _method: post }

admin_secciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Items:edit" }

admin_secciones_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/Items:update" }
    requirements: { _method: post|put }

admin_secciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Items:delete" }
    requirements: { _method: post|delete }

secciones_delete_archivo:
    path:     /{id}/delete-archivo
    defaults: { _controller: "AppBundle:Admin/Items:deleteArchivo" }
    requirements: { _method: post|get }
