<?php

namespace AppBundle\Entity\Front;

use Doctrine\ORM\EntityRepository;

/**
 * ComentariosItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentariosItemsRepository extends EntityRepository
{
}
