services:
    # app.model.items:
    #   class:      AppBundle\Model\ItemModuloModel
    #   arguments:  [@doctrine.orm.entity_manager, @twig, @app.mensajero, @router, @security.context]
    app.model.usuarios:
      class:  AppBundle\Model\ACL\UsuariosModel
      arguments:  [@doctrine.orm.entity_manager]

    app.model.cursos:
      class:  AppBundle\Model\Admin\CursosModel
      arguments:  [@doctrine.orm.entity_manager]

    app.model.modulos:
      class:  AppBundle\Model\Admin\ModulosModel
      arguments:  [@doctrine.orm.entity_manager]

    app.model.items:
      class:  AppBundle\Model\Admin\ItemsModel
      arguments:  [@doctrine.orm.entity_manager]

    app.quiz_manager:
        class:  AppBundle\Model\Admin\QuizManager
        arguments:
            - @doctrine.orm.entity_manager
            - AppBundle\Entity\Admin\Quiz\Quiz
