acl:
    resource: "@AppBundle/Resources/config/routing/acl.yml"
    prefix:   /

acl_roles:
    resource: "@AppBundle/Resources/config/routing/roles.yml"
    prefix:   /admin/acl/roles

acl_usuarios:
    resource: "@AppBundle/Resources/config/routing/usuarios.yml"
    prefix:   /admin/acl/usuarios

admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /

quiz_admin_quiz:
    resource: "@AppBundle/Resources/config/routing/admin/quiz.yml"
    prefix:   /admin/quiz

elearn_admin_secciones:
    resource: "@AppBundle/Resources/config/routing/admin/items.yml"
    prefix:   /admin/secciones

elearn_admin_modulos:
    resource: "@AppBundle/Resources/config/routing/admin/modulos.yml"
    prefix:   /admin/modulos

elearn_admin_cursos:
    resource: "@AppBundle/Resources/config/routing/admin/cursos.yml"
    prefix:   /admin/cursos

elearn_admin_cursos_usuarios:
    resource: "@AppBundle/Resources/config/routing/admin/cursousuarios.yml"
    prefix:   /admin/cursos/usuarios

front:
    resource: "@AppBundle/Resources/config/routing/front/front.yml"
    prefix:   /
