services:
    user_provider:
        class: AppBundle\Utils\UserProvider
        calls:
            - [setContainer, ["@service_container"]]

    temporalidad:
      class:      AppBundle\Utils\Temporalidad
      arguments:  ["@security.context", @doctrine.orm.entity_manager]

    encoder:
      class: AppBundle\Utils\Encoder
      arguments: ['@security.encoder_factory']

    api.elearn.soap:
        class: AppBundle\Utils\APISoap
        arguments:  [@doctrine.orm.entity_manager, @encoder, @mailer, @twig]

    hello:
        class: AppBundle\Utils\Hello

    app.valor_random:
      class:  AppBundle\Utils\ValorRandom

    app.cartero:
      class:  AppBundle\Utils\Cartero
      arguments:  [@mailer]

    app.mensajero:
      class:  AppBundle\Utils\Mensajero
      arguments:  [@session]

    app.usuario_curso:
        class: AppBundle\Utils\UsuarioCurso
        arguments:  [@doctrine.orm.entity_manager]

    app.reporte_cursos_usuarios:
        class: AppBundle\Utils\ReporteCursosUsuarios
        arguments:  [@app.model.cursos, @app.model.usuarios]

    app.modulos_liberados:
        class: AppBundle\Utils\ModulosLiberados
        arguments:  [@app.reporte_cursos_usuarios, @app.cartero, @app.model.usuarios, @app.model.modulos, @twig]
