elearn_comentarios_items:
    resource: "@ElearnBundle/Resources/config/routing/comentariositems.yml"
    prefix:   /comentarios/items

elearn_admin_modulos_secciones:
    resource: "@ElearnBundle/Resources/config/routing/modulosecciones.yml"
    prefix:   /admin/modulos/secciones

elearn_admin_cursos_modulos:
    resource: "@ElearnBundle/Resources/config/routing/cursomodulos.yml"
    prefix:   /admin/cursos/modulos

elearn_homepage:
    path:     /hello/{name}
    defaults: { _controller: ElearnBundle:Default:index }
