elearn_admin_cursos_usuarios:
    resource: "@ElearnBundle/Resources/config/routing/cursousuarios.yml"
    prefix:   /admin/cursos/usuarios

elearn_comentarios_items:
    resource: "@ElearnBundle/Resources/config/routing/comentariositems.yml"
    prefix:   /comentarios/items

elearn_admin_modulos_secciones:
    resource: "@ElearnBundle/Resources/config/routing/modulosecciones.yml"
    prefix:   /admin/modulos/secciones

elearn_admin_cursos_modulos:
    resource: "@ElearnBundle/Resources/config/routing/cursomodulos.yml"
    prefix:   /admin/cursos/modulos

front_perfil:
    path:     /perfil/
    defaults: { _controller: ElearnBundle:Front:perfil }

elearn_admin_secciones:
    resource: "@ElearnBundle/Resources/config/routing/secciones.yml"
    prefix:   /admin/secciones

elearn_admin_modulos:
    resource: "@ElearnBundle/Resources/config/routing/modulos.yml"
    prefix:   /admin/modulos

elearn_admin_cursos:
    resource: "@ElearnBundle/Resources/config/routing/cursos.yml"
    prefix:   /admin/cursos

elearn_homepage:
    path:     /hello/{name}
    defaults: { _controller: ElearnBundle:Default:index }

front_curso:
    path:     /curso/{id}
    defaults: { _controller: ElearnBundle:Front:index }

front_modulo:
    path:     /curso/{curso}/{modulo}/{seccion}/{pregunta}
    defaults: { _controller: ElearnBundle:Front:modulo, pregunta:null }

front_msn:
    path:     /perfil/msn
    defaults: { _controller: ElearnBundle:MSN:msn}

perfil_tus_cursos:
    path:     /perfil/tus-cursos
    defaults: { _controller: ElearnBundle:Front:tusCursos }
