<?php

namespace Elearn\ElearnBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoUsuariosRepository extends EntityRepository
{
}
