<?php

namespace Elearn\ElearnBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MensajesRespuestasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajesRespuestasRepository extends EntityRepository
{
  public function findMensajeRespuesta($id)
  {
    $query = $this->getEntityManager()
      ->createQuery(
        'SELECT m FROM ElearnBundle:MensajesRespuestas m
        WHERE m.mensajes = :mensaje'
      )
      ->setParameter('mensaje', $id);

      try{
        return $query->getSingleResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
         return null;
      }
  }

  public function MensajesUsuario($id)
  {
    $query = $this->getEntityManager()
      ->createQuery(
        'SELECT m FROM ElearnBundle:MensajesRespuestas m
        JOIN m.mensajes r
        WHERE r.usuarios = :usuario'
      )
      ->setParameter('usuario', $id);

      try{
        return $query->getResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
         return null;
      }
  }
}
