<?php

namespace AppBundle\Entity\Admin\Quiz;

use Doctrine\ORM\EntityRepository;

/**
 * QuizUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizUsuarioRepository extends EntityRepository
{
}
