<?php

namespace AppBundle\Entity\Admin\Cursos;

use Doctrine\ORM\EntityRepository;

/**
 * CursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursosRepository extends EntityRepository
{
  public function findCursosPublicados()
  {
    return $this->getEntityManager()
      ->createQuery(
        'SELECT c FROM AppBundle:Admin\Cursos\Cursos c where c.publicado = 1 ORDER BY c.id DESC '
      )
      ->getResult();
  }
}
