<?php

namespace AppBundle\Entity\Admin\Cursos;

use Doctrine\ORM\EntityRepository;

/**
 * CursoUsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoUsuariosRepository extends EntityRepository
{
  public function findCursosUsuarios($curso, $usuario)
  {
    return $this->getEntityManager()
      ->createQuery(
        'SELECT c FROM AppBundle:Admin\Cursos\CursoUsuarios c where c.cursos = :curso AND c.usuarios = :usuario'
      )
      ->setParameter('curso', $curso)
      ->setParameter('usuario', $usuario)
      ->getResult();
  }

  public function registroCursoUsuario($curso, $usuario)
  {
    return $this->getEntityManager()
      ->createQuery(
        'SELECT c FROM AppBundle:Admin\Cursos\CursoUsuarios c where c.cursos = :curso AND c.usuarios = :usuario'
      )
      ->setParameter('curso', $curso)
      ->setParameter('usuario', $usuario)
      ->getSingleResult();
  }

  public function findCursoUsuario($curso, $usuario)
  {
    return $this->getEntityManager()
      ->createQuery(
        'SELECT c FROM AppBundle:Admin\Cursos\CursoUsuarios c where c.cursos = :curso AND c.usuarios = :usuario'
      )
      ->setParameter('curso', $curso)
      ->setParameter('usuario', $usuario)
      ->getResult();
  }
}
