<?php

namespace AppBundle\Entity\Admin\Cursos;

use Doctrine\ORM\EntityRepository;

/**
 * CursoModulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoModulosRepository extends EntityRepository
{
}
