<?php

namespace AppBundle\Entity\Admin\Cursos;

use Doctrine\ORM\EntityRepository;

/**
 * CursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursosRepository extends EntityRepository
{
  public function findCursosPublicados()
  {
    return $this->getEntityManager()
      ->createQuery(
        'SELECT c FROM AppBundle:Admin\Cursos\Cursos c where c.publicado = true ORDER BY c.id DESC '
      )
      ->getResult();
  }

  public function findCursoModuloItem($cursoId, $moduloId, $itemId)
  {

      $em = $this->getEntityManager();

      $cursos = $em->getRepository('AppBundle:Admin\Cursos\Cursos');

      $curso = $cursos->createQueryBuilder('c')
        ->select('c','cm','m','i')
        ->leftJoin('c.modulos','cm')
        ->leftJoin('cm.modulos', 'm')
        ->leftJoin('m.items','i')
        ->where('c.id = :curso')
        ->andWhere('cm.modulos = :modulo')
        ->andWhere('i.items = :item')
        ->setParameter('curso', $cursoId)
        ->setParameter('modulo', $moduloId)
        ->setParameter('item', $itemId)
        ->getQuery()
        ->getArrayResult()
      ;

      return $curso;

  }
}
