<?php

namespace AppBundle\Entity\Admin\Modulos;

use Doctrine\ORM\EntityRepository;

/**
 * ModulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulosRepository extends EntityRepository
{
}
