comentarios_items:
    path:     /
    defaults: { _controller: "ElearnBundle:ComentariosItems:index" }

comentarios_items_show:
    path:     /{id}/show
    defaults: { _controller: "ElearnBundle:ComentariosItems:show" }

comentarios_items_new:
    path:     /new
    defaults: { _controller: "ElearnBundle:ComentariosItems:new" }

comentarios_items_create:
    path:     /create
    defaults: { _controller: "ElearnBundle:ComentariosItems:create" }
    methods:  POST

comentarios_items_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElearnBundle:ComentariosItems:edit" }

comentarios_items_update:
    path:     /{id}/update
    defaults: { _controller: "ElearnBundle:ComentariosItems:update" }
    methods:  [POST, PUT]

comentarios_items_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElearnBundle:ComentariosItems:delete" }
    methods:  [POST, DELETE]
