admin_modulos_secciones:
    path:     /{modulo}
    defaults: { _controller: "ElearnBundle:ModuloSecciones:index" }

admin_modulos_secciones_show:
    path:     /{id}/show
    defaults: { _controller: "ElearnBundle:ModuloSecciones:show" }

admin_modulos_secciones_new:
    path:     /new
    defaults: { _controller: "ElearnBundle:ModuloSecciones:new" }

admin_modulos_secciones_create:
    path:     /create
    defaults: { _controller: "ElearnBundle:ModuloSecciones:create" }
    methods:  POST

admin_modulos_secciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElearnBundle:ModuloSecciones:edit" }

admin_modulos_secciones_update:
    path:     /{id}/update
    defaults: { _controller: "ElearnBundle:ModuloSecciones:update" }
    methods:  [POST, PUT]

admin_modulos_secciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElearnBundle:ModuloSecciones:delete" }
    methods:  [POST, DELETE]

admin_modulo_item_delete:
    path:     /{modulo}/{item}/delete
    defaults: { _controller: "ElearnBundle:ModuloSecciones:deleteItemModulo" }
    methods:  [GET]
